name: Flutter Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v4
        with:
          flutter-version: '3.19.5'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NourSmartConsulor
          path: build/app/outputs/flutter-apk/app-release.apk
